version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/backend
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:15.3
    ports:
      - 127.0.0.1:5432:5432
