"""empty message

Revision ID: 99490647f6a1
Revises: 5094748e8c31
Create Date: 2024-09-24 13:22:08.639781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99490647f6a1'
down_revision = '5094748e8c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Enum('GOALKEEPER', 'DEFENDER', 'MIDFIELDER', 'FORWARD', name='positions'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('club')
    op.execute("DROP TYPE positions;")
    # ### end Alembic commands ###
